### ISSUE TITLE
Is there a way to hide StatusBar for .fullScreen Presentr type?

### ISSUE THREAD

**Issue by annjawn** [IcaliaLabs/Presentr#103]
I am trying to hide the status bar on a View controller that I am presenting in `.fullScreen` mode using Presentr. However using the below code in the View controller doesn't seem to be working-

```
override var prefersStatusBarHidden: Bool {
    return true
}
```

I have also set the "View controller-based status bar appearance" value to YES in info.plist, but the status bar still shows up.

**Comment by jackngai** [comment]
I was going to write that I have the same problem, but I figured out a solution. I end up hiding the status bar right  before presenting the view using Presentr. Then I use the closure in customPresentViewController to change the boolean value to unhide the status bar. I don't call setNeedsStatusBarAppearanceUpdate in the block so it doesn't show the status bar as soon as the view is shown, but it will show the status bar as soon the view is dismissed. Here's the code. 

```
    var hideStatusBar = false
    
    override var prefersStatusBarHidden: Bool {
        return hideStatusBar
    }

// In method that presents the controller using Presentr
        hideStatusBar = true
        setNeedsStatusBarAppearanceUpdate()
        customPresentViewController(presenter, viewController: controllerToPresent, animated: true){
            self.hideStatusBar = false
        }
```

**Comment by annjawn** [comment]
@jackngai there's a much easier solution. In the parent Viewcontroller before you call `customPresentViewController` method with your custom View controller, you just need to do `customVC.modalPresentationCapturesStatusBarAppearance = true` this will hand over the status bar's appearance and visibility to the presentr vc. For example-

```
let customViewController: StorePickupYNVC = {
            let customViewController = self.storyboard?.instantiateViewController(withIdentifier: "customvc") as! CustomVC
            return customViewController
        }()
        customViewController.modalPresentationCapturesStatusBarAppearance = true        
        customPresentViewController(presentr, viewController: customViewController, animated: true, completion: nil)
```

And then in the Presentr's View Controller you can do

```
    //to hide the status bar
    override var prefersStatusBarHidden: Bool{
        return true
    }

    //to change the status bar to white color
    override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }

```

**Comment by jackngai** [comment]
Cool! Thanks for sharing this.
