### ISSUE TITLE
ViewControllers (call it A) presentr'd with a custom type that presents another view controller (call it B), upon dismissal of B and returning to A, has it stretched before returning back to normal.

### ISSUE THREAD

**Issue by apollow** [IcaliaLabs/Presentr#104]
Can't tell if this issue is a duplicate or not, let me know.

**Comment by annjawn** [comment]
Yes, duplicate. See #102  and #68

**Comment by danlozano** [comment]
Thanks @annjawn 

Yep. This seems to be an issue with Apple's SDK's and the custom view controller presentation API's that Presentr uses under the hood.

Issue #68 , scroll to the bottom, and the last 2-3 comments have a couple of solutions I found.

I think I might dedicate some more time to this issue, maybe find a more permament workardound. Or at least add the workarounds I already found to the docs.
