### ISSUE TITLE
It seems shouldIgnoreTapOutsideContext doesn't work as expected

### ISSUE THREAD

**Issue by ab-rdarts** [IcaliaLabs/Presentr#105]
As I understand shouldIgnoreTapOutsideContext should enable passthrough, but it doesn't work in all cases. Please look at screenshot. As I understand at top I see chromeView which intercepts taps and backgroundView doesn't work as expected. I can move tableview only in center of the screen but not at top of the screen (where the transparent yellow color is visible).

```
    let customBackgroundPresenter: Presentr = {
        let width = ModalSize.full
        let height = ModalSize.custom(size: 200)
        let center = ModalCenterPosition.customOrigin(origin: CGPoint(x: 0, y: 667-200))
        let customType = PresentationType.custom(width: width, height: height, center: center)
        
        let customPresenter = Presentr(presentationType: customType)
        customPresenter.transitionType = .coverVertical
        customPresenter.dismissTransitionType = .coverVertical
        
        customPresenter.backgroundColor = .yellow
        customPresenter.backgroundOpacity = 0.5
        
        customPresenter.shouldIgnoreTapOutsideContext = true
        customPresenter.dismissOnTap = false
        customPresenter.dismissOnSwipe = false
        
        let view = UIImageView(image: #imageLiteral(resourceName: "Logo"))
        //view.frame = CGRect(x: UIScreen.main.bounds.width / 2 - 50, y: UIScreen.main.bounds.height / 2 - 50, width: 100, height: 100)
        view.contentMode = .scaleAspectFit
        //customPresenter.customBackgroundView = view

        return customPresenter
    }()

...

    func customBackgroundPresentation() {
        customBackgroundPresenter.viewControllerForContext = self
        customPresentViewController(customBackgroundPresenter, viewController: alertController, animated: true, completion: nil)
    }
```

![simulator screen shot aug 5 2017 11 28 37 am](https://user-images.githubusercontent.com/9376541/28994216-76836166-79d1-11e7-9e06-3616b7c69260.png)

**Comment by danlozano** [comment]
Hi!

I'm a little confused at the view controller/container situation you got going on there.

Could you send me a sample project or a little more code and context to try and figure out what is going on?

Any ideas on why your case is different from the basic sample case in the example project? or is that not working the way you think it should either?

**Comment by danlozano** [comment]
Will close until further code/samples provided.
