### ISSUE TITLE
Swipe to dismiss animation

### ISSUE THREAD

**Issue by anthonycastelli** [IcaliaLabs/Presentr#11]
The little x at the top right and the swipe animation don't appear to be present.

**Comment by danlozano** [comment]
Hi!

Oh I see what you mean. Are you talking about the X in the screenshots? Those are not part of Presentr, those are part of that app's design (the one I took the screenshots in).

To dismiss the presented controller there are currently two ways. One is tapping on the background, and the other is calling dismissViewController:animated yourself from the view controller you presented.

What do you mean by the swipe animation?

**Comment by anthonycastelli** [comment]
Yeah, the X at the top right and the bottom arrow. Maybe have an option to show one or the other? I think they will be handy. As for the swipe animation, like an interactive dismiss animation similar to tweetbot or messages image dismissal. From the demo images, I thought there was such a thing already implemented.

**Comment by danlozano** [comment]
Oh ok.

Yeah I think I could add the X to make the dismissal more obvious, there could be an optional property to show it or not. Will add this to the next release.

Adding interactive presentation/dismissal is definitely something I want to look into, but I don't think I can work on it for the next relase, but definitely somewhere along the line. If someone wants to help with that via a pull request that would be cool!

**Comment by josejuanqm** [comment]
#34
