### ISSUE TITLE
iOS 11, Swift 4 -- Swipe to dismiss

### ISSUE THREAD

**Issue by Huddie** [IcaliaLabs/Presentr#110]
When I try swiping to exit there is a major stutter. 
If you could update for swift 4 that would be awesome. Love the framework

**Comment by Patchivic** [comment]
+1

**Comment by falkobuttler** [comment]
+1

**Comment by malkouz** [comment]
+1

**Comment by danlozano** [comment]
Any swift 4 problems please refer to this other issue #112 

Thanks.
