### ISSUE TITLE
presenting views on top of presenter issue

### ISSUE THREAD

**Issue by pprevalon** [IcaliaLabs/Presentr#111]
i have a presentr view shown on top of of the screen if I present a view on top of presentr then dismiss the view the is a slight flicker of the presentr view, it shows it full screen then it goes to the top of the scree the way it is suppose to be. have you experience this issue or known of it.

**Comment by zvving** [comment]
@pprevalon I has some issue with you.

- Use `Presentr` present show ViewControllerA with half type.
- Present ViewControllerB in ViewControllerA
- Try dismiss ViewControllerB. The ViewControllerA show FullScreen and fast show half screen.

How fix it? Thx!

**Comment by zvving** [comment]
Same with https://github.com/IcaliaLabs/Presentr/issues/68

**Comment by zvving** [comment]
I try `secondVC.modalPresentationStyle = .overFullScreen` fixed my issue.

**Comment by danlozano** [comment]
Yeah, it's a known Apple SDK issue with custom view controller presentation.

I outlined a couple of fixes/workarounds in #68
