### ISSUE TITLE
Swift 4 Build Problem

### ISSUE THREAD

**Issue by rezabina86** [IcaliaLabs/Presentr#112]
I got this error on build on xcode 9 : 
Struct 'PresentrConstants' is internal and cannot be referenced from a default argument value.

Please help

**Comment by Huddie** [comment]
+1

**Comment by gabber3000** [comment]
+1

**Comment by FranciscoMkdir** [comment]
+1

**Comment by JFERSD** [comment]
Is this going to be fixed soon?

**Comment by danlozano** [comment]
Yes! Will get around to this probably today.

Sorry for the delay!

Just so I have all available information. That's the only issue you are getting on Swift4/Xcode9?

I had tested it before and thought everything would work ok in Swift 3.2 compatibility mode, but apparently not. Will check it out today. Any more info/bugs you have I would appreciate to fix it all in one swoop!

**Comment by danlozano** [comment]
Version 1.3 is out with Swift 4/3.2 support.

Please try it out and open a new issue if any new bug pops out. 

I will be focusing on this these days so it should not take any time to fix any new issue. I want to leave this version 100% stable.

Thanks for your patience.
