### ISSUE TITLE
Initializer for conditional binding must have Optional type, not 'CGFont'

### ISSUE THREAD

**Issue by salah-mohammed** [IcaliaLabs/Presentr#115]
static func loadFont(_ name: String) -> Bool {
        let bundle = Bundle(for: self)
        guard let fontPath = bundle.path(forResource: name, ofType: "ttf"),
            let data = try? Data(contentsOf: URL(fileURLWithPath: fontPath)),
            let provider = CGDataProvider(data: data as CFData),
            let font = CGFont(provider)
        else {
            return false
        }

        var error: Unmanaged<CFError>?

        let success = CTFontManagerRegisterGraphicsFont(font, &error)
        if !success {
            print("Error loading font. Font is possibly already registered.")
            return false
        }

        return true
    }

in             let font = CGFont(provider)
 error 
swift 4.0

**Comment by danlozano** [comment]
Which version of Swift are you using?

Swift 4 uses an optional for CGFont so it shouldn't have that error.

Are you using Swift 3.1 / Xcode 8?

Or swift 3.2 / Xcode 9?

**Comment by danlozano** [comment]
Try removing `let font = CGFont(provider)` from the `guard` statement and adding this code below.

```swift
#if swift(>=3.2)
    guard let font = CGFont(provider) else {
        print("Error loading font. Could not create CGFont from CGDataProvider.")
        return false
    }
#else
    let font = CGFont(provider)
#endif
```

Let me know if it works for you. If it does I'll add it.

**Comment by salah-mohammed** [comment]
xcode 9.0 
swift 3.2

**Comment by danlozano** [comment]
Hmm sorry, it's been kind of confusing making it work with both Swift 4 and Swift 3.2 at the same time.

If the above code doesn't work try this out.

```swift
#if swift(>=4)
    guard let font = CGFont(provider) else {
        print("Error loading font. Could not create CGFont from CGDataProvider.")
        return false
    }
#else
    let font = CGFont(provider)
#endif
```

Let me know please. I tried to test both 3.2 and 4 cases on my machine but apparently I missed something.

**Comment by alediaz84** [comment]
Same issue here. Xcode 9, swift 4.0

**Comment by tjarbo** [comment]
@alediaz84 How were your steps? Because it still doesn't work, after I changed the Swift-Language-Version for my Project and my Targets to Swift 4.0 ?

**Comment by alediaz84** [comment]
I just changed the pod swift version to 4.0 and used 1.3 version. The project is configured with CocoaPods.

**Comment by danlozano** [comment]
Nice!

So changing the pods project to swift 4 makes it work fine?

Will hold off on the "fix" for now then. If more people have this issue I might add the above fix code.

Thanks @alediaz84

**Comment by danlozano** [comment]
I'll leave this open to continue conversation if more people get this issue.

**Comment by cmtrounce** [comment]
I am also experiencing this issue.

**Comment by mollywoodnini** [comment]
I have the same problem.

**Comment by alediaz84** [comment]
@cmtrounce 
@mollywoodnini 
Please, check that Presentr 1.3 is being compiled with swift 4 instead of Swift 3.2

**Comment by retuner87** [comment]
Hi, changing "Swift Language Version" on Pod > Presentr > Build Settings to Swift 4.0 it works.
Thanks

**Comment by farooq94** [comment]
Using Swift 4, xcode 9, still getting this error
Initializer for conditional binding must have Optional type, not 'CGFont'

**Comment by danlozano** [comment]
@farooq94 Have you tried changing the Build Settings to Swift 4?
