### ISSUE TITLE
Custom presentations don't render properly in landscape mode

### ISSUE THREAD

**Issue by dafurman** [IcaliaLabs/Presentr#116]
Check out Custom presentation in the sample app and press it when in landscape mode to see what I mean.

I have my own issue fitting the entire height of a view when presenting from the bottom center when trying to display a view in landscape mode. The view is cut off at the bottom of the screen.

**Comment by danlozano** [comment]
You can try the new `ModalSize` type of `.customOrientation` which let's you select a different size for landscape/portrait orientations.

Would that work for you?

**Comment by danlozano** [comment]
Please re-open issue if you want to look further into this.

Thanks!
