### ISSUE TITLE
Presentr auto calculate viewController height

### ISSUE THREAD

**Issue by pprevalon** [IcaliaLabs/Presentr#117]
Im currently using .top to present my UItableView with no footer. I want Presentr to calculate the height and show all the visible cell instead of me setting the height i would like for Presentr to calculate that. How can i complete this? thank you in advance.

**Comment by mamnun** [comment]
`Presentr` should not calculate the height. If you properly set  your VC autolayout constraints and use dynamic presentation type you can achieve this. 

One approach would be setup a `heightConstraint` for your VC. then in the scrollview(which is your tableview) delegate, you set the `heightContraint` value to the `contentSize.height`.

**Comment by danlozano** [comment]
Sorry. Been really busy with work. 

Will get a couple of weeks of for the holidays and will catch up on issues and pull requests. Thanks for your patience.

**Comment by danlozano** [comment]
If you wan't auto layout dynamic sizing you should use the .dynamic PresentationType.

Let me know if that work's out.
