### ISSUE TITLE
how to set a height for  'let customPresenter = Presentr(presentationType: .bottomHalf)'

### ISSUE THREAD

**Issue by pprevalon** [IcaliaLabs/Presentr#119]
Im trying to get the same effect as the .bottomHalf but i want to specify my own height. I try '        let height = ModalSize.custom(size: 100)' but what should I set ModalCenterPosition to.

**Comment by danlozano** [comment]
Sorry. Been really busy with work. 

Will get a couple of weeks of for the holidays and will catch up on issues and pull requests. Thanks for your patience.

**Comment by danlozano** [comment]
Hi!

The `.bottomHalf` Presentation Type does exactly what it's name implies. If fills the bottom half, so it would make no sense to "change" the height for that.

What exactly are you trying to accomplish? A view that is of X height but it's on the bottom of the screen?

You could accomplish that with a `ModalCenterPosition` with a customOrigin of X = 0; Y = screen.height - your height.

But let me know exactly what you wanted to do, to see if we can add a new type or sizing option, if enough people wan't something similar.

**Comment by apptekstudios** [comment]
We rewrote the positioning/layout part of this library for more flexibility if you want to check out our fork @pprevalon. We haven't had a chance to document/fully test yet

Example use:
`let layout = ModalLayout(width: .inset(by: 20), height: .autolayout, positionReference: .bottomMiddle, position: .bottom)`
`let customType = PresentationType.custom(layout: layout)`
`let customPresenter = Presentr(presentationType: customType)`

**Comment by danlozano** [comment]
Hi @apptekstudios ,

Oh nice! 

I don't see the repo 🤔 ... If you guys are willing to do a Pull Request, so I can check it out and test it and maybe we can add it to the library.

Thanks

**Comment by apptekstudios** [comment]
Hi @danlozano,
I'll try find time to clean it up a little this afternoon and put through a pull request. It would be code-breaking in it's current form as I removed the old layout api (although you certainly could keep both until a major version)

**Comment by apptekstudios** [comment]
@danlozano I've made the PR #142

**Comment by danlozano** [comment]
This sounds awesome!

Will check it out and see what would be the best way to handle this. Probably having both options for now would be best.

I'll let you know if I have any questions.

Thanks @apptekstudios !!

**Comment by danlozano** [comment]
We'll discuss this in the PR, so I'll close this issue.
