### ISSUE TITLE
Customise transition when dismissing

### ISSUE THREAD

**Issue by tbaranes** [IcaliaLabs/Presentr#12]
For example: present the viewController with `CoverHorizontalFromLeft` then dismiss it using `CoverHorizontalFromRight`.

It could be useful for more advanced use case :)

**Comment by danlozano** [comment]
So basically the default would be to use the same transition for presentation & dismissal, BUT have an optional way of setting different presenting and dismissing transitions.

Good idea! Will definitely look into this for next release.

**Comment by danlozano** [comment]
#13 fixes this issue!

will add this and some other bug fixes to next release

**Comment by danlozano** [comment]
I just realized you were the issue and pull request author @tbaranes thought you were different users haha.

**Comment by tbaranes** [comment]
Haha. I got a good timing! I opened the issue and only then I decided to implement it 😁

**Comment by danlozano** [comment]
Nice!

Check out 0.1.7 should have this and some other pull requests I merged. See the readme as well, I added it in the "what's new" and in the instructions.

**Comment by tbaranes** [comment]
I'm gonna give a try to 0.1.7!
By the way, do you have any CHANGELOG or detailed released?

**Comment by danlozano** [comment]
I added a "What's New" section to the Readme.

Do you think it's OK? or should there be a separate/more detailed CHANGELOG?

hmmm

**Comment by danlozano** [comment]
I should also add the contributors in there!

**Comment by tbaranes** [comment]
It can be ok for now, but your README will be quickly flooded by that section, could be worth to move it in a CHANGELOG file, even if it's not more detailed.

**Comment by danlozano** [comment]
Good idea, will do.
