### ISSUE TITLE
Observe dismiss?

### ISSUE THREAD

**Issue by mrdaios** [IcaliaLabs/Presentr#121]
https://github.com/IcaliaLabs/Presentr/blob/67eef3e9974d8125cc169c111c56e14e45a6a017/Presentr/PresentrController.swift#L363
how can i Observe this?

TKS.

**Comment by danlozano** [comment]
Sorry. Been really busy with work. 

Will get a couple of weeks of for the holidays and will catch up on issues and pull requests. Thanks for your patience.

**Comment by aasatt** [comment]
You can currently do so by conforming your presented view controller to `PresentrDelegate` you will get a callback just before dismiss. If you want to be notified in the controller that presented it, you can create a delegate between your two controllers to let the presenting one know.

Example: 

FirstViewController presents SecondViewController

In `SecondViewController.swift`:

```
protocol SecondViewControllerDelegate {
    
    func presentrShouldDismiss() -> Bool
    
}

class SecondViewController: UIViewController, PresentrDelegate {

    var delegate: SecondViewControllerDelegate

    convenience init(delegate: SecondViewControllerDelegate) {
        self.init(nibName: nil, bundle: nil, delegate: delegate)
    }
    
    init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?, delegate: SecondViewControllerDelegate) {
        self.delegate = delegate
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func presentrShouldDismiss(keyboardShowing: Bool) -> Bool {
        return delegate.presentrShouldDismiss()
    }

}
```

In `FirstViewController.swift`

```
extension FirstViewController: SecondViewControllerDelegate {
    
    @objc func actionPresentNotificationHub(sender: UIBarButtonItem) {
        customPresentViewController(notificationPresentr, viewController: SecondViewController(delegate: self), animated: true, completion: nil)
    }
    
    func presentrShouldDismiss() -> Bool {
        // perform any actions you need to do
        return true
    }
    
}

```

**Comment by danlozano** [comment]
Yes, @aasatt is correct. Thanks dude 👍 

If you have any more doubts you can re-open issue.

**Comment by mrdaios** [comment]
it's work.
