### ISSUE TITLE
Push latest changes to Pod Trunk?

### ISSUE THREAD

**Issue by cameronehrlich** [IcaliaLabs/Presentr#122]
We have `Presentr` as a dependency in private .podspec for our teams' shared code.  Anything I can do to help speed this along? 

Thanks!

~ Cam

**Comment by danlozano** [comment]
Sorry. Been really busy with work. 

Will get a couple of weeks of for the holidays and will catch up on issues and pull requests. Thanks for your patience.

**Comment by danlozano** [comment]
Done as of today 👍
