### ISSUE TITLE
Round corners not working in iPhoneX

### ISSUE THREAD

**Issue by otymartin** [IcaliaLabs/Presentr#124]
@danlozano 
Rounding corners for custom PresentationTypes doesn't work in iPhone X for whatever reason despite the method being called.

I have shouldRoundCorners as true for all presentation types.

**Comment by danlozano** [comment]
Sorry. Been really busy with work. 

Will get a couple of weeks of for the holidays and will catch up on issues and pull requests. Thanks for your patience.

**Comment by danlozano** [comment]
<img width="508" alt="screen shot 2018-04-21 at 8 58 13 pm" src="https://user-images.githubusercontent.com/2406956/39090510-ba9ee022-45a6-11e8-861c-2472e5cdfba5.png">

**Comment by danlozano** [comment]
It seems to be working OK in the example project.

Could you give me a little more insight into your code to track down what is going wrong?

Thanks

**Comment by otymartin** [comment]
@danlozano Will recheck this, It works in all cases except for my custom presenter VC that plays back video.

I'll reinvestigate.

Thanks

**Comment by danlozano** [comment]
Thank you! Please let me know and if you find anything out please re-open the issue!

Could it that the video/view/layer needs to be clipped to respect the rounded corners? 🤔
