### ISSUE TITLE
overCurrentContext in Custom Container

### ISSUE THREAD

**Issue by pkuklis** [IcaliaLabs/Presentr#127]
Hi,

Is it possible to create transitions in Presentr that work similarly to .overCurrentContext?

I have a custom containerViewController (which displays buttons) and would like to perform a segue from the first childViewController to the second one (without overlaying the container).

Here's a quick example:
https://youtu.be/v8V8-uw0oco

Would love to know if it's feasible!

**Comment by danlozano** [comment]
Hi!

Nice video! But could you elaborate a little bit more so I can understand.

If you want to you can create a custom `PresentrAnimation`. I'm pretty sure all presentations with Presentr behave like .overCurrentContext

What exactly are you missing or having trouble with?

Thanks!

**Comment by danlozano** [comment]
Please open if needed.
