### ISSUE TITLE
Presentr animation from corner

### ISSUE THREAD

**Issue by freakdragon** [IcaliaLabs/Presentr#130]
May be, it will be useful for someone, or the author will add it to release (desirable, in 3.0 swift :) ).
The code of corner animation, based on author's animations.

```
import Foundation
import Presentr

public class CoverFromCornerAnimation: PresentrAnimation {
    
    private var fromBottom: Bool
    private var fromRight: Bool
    
    public init(fromBottom: Bool = false, fromRight: Bool = false) {
        self.fromBottom = fromBottom
        self.fromRight = fromRight
    }
    
    override public func transform(containerFrame: CGRect, finalFrame: CGRect) -> CGRect {
        var initialFrame = finalFrame
        if(fromBottom) {
            initialFrame.origin.y = containerFrame.size.height + initialFrame.size.height
        } else {
            initialFrame.origin.y = 0 - initialFrame.size.height
        }
        if(fromRight) {
            initialFrame.origin.x = containerFrame.size.width + initialFrame.size.width
        } else {
            initialFrame.origin.x = 0 - initialFrame.size.width
        }
        return initialFrame
    }
    
}
```

The usage is simple.
From left top corner:

`presenter.transitionType = TransitionType.custom(CoverFromCornerAnimation())`

From left bottom corner:

`presenter.transitionType = TransitionType.custom(CoverFromCornerAnimation(fromBottom: true))`

From right top corner:

`presenter.transitionType = TransitionType.custom(CoverFromCornerAnimation(fromRight: true))`

From right bottom corner:

`presenter.transitionType = TransitionType.custom(CoverFromCornerAnimation(fromBottom: true, fromRight: true))`

**Comment by danlozano** [comment]
Interesting  new animation.

Could you open a Pull Request so I can test it out and further take a look into it.

Thanks.
