### ISSUE TITLE
Device rotation

### ISSUE THREAD

**Issue by crspybits** [IcaliaLabs/Presentr#133]
Hi-- I like Presentr-- I'm using it in two projects so far. One question: Is there a way to change the (x, y) position of the origin of the presented modal with device rotation? I'd like to drop the modal below the status bar in portrait mode, and keep it at the top in landscape. Thanks.

**Comment by danlozano** [comment]
Maybe this isssue #134 could help out.

Anyways, if you want to change the position just changing the frame of the presented view controller (from inside the VC) should work.

If that doesn't work out, please open a new issue and I'll look further into it.

:)
