### ISSUE TITLE
NavigationController not showing up

### ISSUE THREAD

**Issue by FabylouV** [IcaliaLabs/Presentr#136]
Hi,

When I'm using presentr to display my VC, I'm losing my navigationController.
It's really annoying, I can see the navigation controller on my storyboard, but as soon as I'm using presentr (I'm using it to display a VC as a side bar menu, but still want to keep hierarchy in my VC).

Is there a way to specify the navigation controller ?

Btw, I'm using "customPresentViewController" func to display my VC.

**Comment by danlozano** [comment]
Hi @FabylouV !

If you want to present the hierarchy `Navigation Controller -> Your View Controller` you must present the navigation controller (the one from your storyboard) which includes your view controller as it's child.

Or wrap your view controller in code, inside a Navigation Controller, and then present that.

**Comment by FabylouV** [comment]
Could you give me an example of each, because I'm really not following :x

I tried to do
`VC1.customPresentViewController(presenter, viewController: VC2.navigationController!, animated: true, completion: nil)`
But the VC2.navigationController is nil

**Comment by FabylouV** [comment]
I fixed my issue.

I had a big misunderstanding between displaying modally and dsplaying using hierarchy.
So I displayed my SideBar modally, but I pass the viewController in parameters so once I clicked on an item from my sideBar, I could load the view using hierarchy from my previous navigationController.

**Comment by danlozano** [comment]
Awesome, yeah sounds about right.

Glad you fixed it. 👍
