### ISSUE TITLE
Presenting ViewController with custom UIViewAnimationOptions

### ISSUE THREAD

**Issue by omidgolparvar** [IcaliaLabs/Presentr#137]
Hi 
Please add a property for setting `UIViewAnimationOptions` for presenting ViewController. For example, in some cases, I want to present my ViewControllers with `UIViewAnimationOptions.curveEaseInOut`.

Thanks.

**Comment by danlozano** [comment]
Hi!

When presenting view controllers you can set the `transitionType` to any of the system or presentr provided animations.

If you can't find one that fits what you want, you would need to create your own `PresentrAnimation` which is explained in the Readme.

If you believe its useful for other people, you can create a Pull Request to add your animation to Presentr.

:) Thanks
