### ISSUE TITLE
How to make Presentr custom dialog common in all view controllers

### ISSUE THREAD

**Issue by Karthiccc** [IcaliaLabs/Presentr#141]
what I want to do is to create a presentr custom dialog which should be able to be displayed in all the view controllers. but from your project I can make a presentr object for one view controller and use that to create a dialog. But I want that presentr to be common to view in all view controllers. so the dialog can be appeared in all view controllers.

**Comment by Karthiccc** [comment]
var presenter: Presentr = {
            let width = ModalSize.full
            let height = ModalSize.custom(size: (Float(self.collectionView.frame.height + 5)))
            let center = ModalCenterPosition.customOrigin(origin: CGPoint(x:0, y: relativeHeight))
            let customType = PresentationType.custom(width: width, height: height, center: center)
            
            let customPresenter = Presentr(presentationType: customType)
            customPresenter.transitionType = .crossDissolve
            customPresenter.roundCorners = false
            customPresenter.dismissOnTap = false
            // customPresenter.backgroundColor = .green
            customPresenter.backgroundOpacity = 0
            return customPresenter
        }()
        let filterViewController = storyboard!.instantiateViewController(withIdentifier: "FilterListViewController")
        customPresentViewController(presenter, viewController: filterViewController, animated: true, completion: nil)

what am im doing here is I have custom view controller to be presented using presentr. but this must  common so that I can use that custom presentr in any view controller. I cannot create the presentr object in separate modal class gives me an error saying that it should be viewcontroller to create presentr object

**Comment by Karthiccc** [comment]
and also one more issue is that if the custom dialog is presented. I should be able to access the background view controls when the custom dialog is presented. it should not dismiss on tapping outside it should be able to tap on whatever UI control is at the background view controller.

**Comment by danlozano** [comment]
Hi @Karthiccc ,

You must instantiate and hold onto a Presentr object in any ViewController you want to do custom presentation's, as the Presentr object acts as the delegate for the presentation. This object should not be shared between different view controllers if you want to avoid some possible weirdness.

If you want to avoid code duplication, what you can do is create a static/factory method that creates, configures and returns the Presentr object, but then every view controller that want's to use it has it's own.

On your 2nd point, Presentr currently does not support being able to tap the background view controller, unless you use a custom presentation context, but that applies mostly to split view controller situations.
