### ISSUE TITLE
viewDidAppear / viewWillAppear isn't called after dismissing a presented view controller

### ISSUE THREAD

**Issue by chryb** [IcaliaLabs/Presentr#143]
The viewDidAppear method isn't called after I call the dismiss(animated: true, completion: nil) method. Am I wrong or is this behavior not possible?

**Comment by dosymbaev** [comment]
@chryb Did you find a solution for your problem?

**Comment by naqi** [comment]
I am noticing this as well. None of the viewDid/Will methods are getting called.

**Comment by wangxue-holla** [comment]
I have this problem too

**Comment by wangxue-holla** [comment]
> I am noticing this as well. None of the viewDid/Will methods are getting called.

Did you find a solution for your problem?

**Comment by wangxue-holla** [comment]
@chryb @naqi @dosymbaev

**Comment by wangxue-holla** [comment]
@naqi  @dosymbaev @chryb  @dosymbaev  Did you find a solution for your problem?
