### ISSUE TITLE
Option to handle when keyboard appears

### ISSUE THREAD

**Issue by tbaranes** [IcaliaLabs/Presentr#15]
What about an option to handle keyboard appears? That could something like the following enum:

```swift
enum ActionWhenKeyboardAppears {
case Nothing
case MoveToTop
case MoveAboveKeyboard
}
```

Will be useful when there textfields / textview in the popup!

**Comment by tbaranes** [comment]
Will be closed by #16

**Comment by aasatt** [comment]
Yeah. That's funny that you opened this while I was working on it. I just came across this library yesterday and needed this in my app.

**Comment by danlozano** [comment]
I thought the issue and pull request were by the same user!

This issue had not occurred to me, but I think it will be a pretty common case. @aasatt you were still working on the pull request, right?

👍

**Comment by aasatt** [comment]
@danlozano yeah. I should have something in the next 20 mins after i test it a little more.

**Comment by gabrielPeart** [comment]
@danlozano @aasatt Any news about this issue?

**Comment by danlozano** [comment]
@aasatt was working on this issue inthe #18 pull request.

It still was/is a work in progress, so I left some comments over there on the pull request's thread.

Any more input on your side @gabrielPeart would be welcome.

**Comment by aasatt** [comment]
Yes. Still working on things. Haven't had a chance to revisit it yet.

**Comment by gabrielPeart** [comment]
Cool @aasatt thanks for helping!
