### ISSUE TITLE
Can't we add custom text to it? If yes, then how?

### ISSUE THREAD

**Issue by Kanishka3** [IcaliaLabs/Presentr#153]

**Comment by danlozano** [comment]
Hi!

Add custom text to what? Please specify :) 

Thanks

**Comment by Kanishka3** [comment]
Adding custom text to a Presentr view. Just like I initialized a Presentr. 
var presentr = Presentr(presentationType: .alert) 
Now, how can I edit the text of that Presentr View.

**Comment by cliftonlabrum** [comment]
@Kanishka3 When you present the view, you can specify which view controller you show. So you can put anything you want in your custom view controller and then present it with a `Presentr` object.

```
class PopupAlertViewController: UIViewController{
  //Whatever you want in here...
}
```
...and then:
```
class ViewController: UIViewController{
  @IBAction func tapShowPopup(_ sender: UIButton) {
    //Specify the storyboard that has your Popup alert
    let storyboard = UIStoryboard(name: "Main", bundle: nil)

    //Reference the popup alert specifically (be sure to give it a storyboard ID and the class)
    if let vc = storyboard.instantiateViewController(withIdentifier: "AlertPopup") as? PopupAlertViewController{

      let presenter = Presentr(presentationType: .alert)
      self.customPresentViewController(presenter, viewController: vc, animated: true)

    }
  }
}

**Comment by danlozano** [comment]
Thanks @cliftonlabrum !

Expanding on what was already said. Presentr is basically a wrapper for Apple's `Custom Modal Presentation API`.

Makes it easy to present any of your view controllers with custom position, sizing and animations.

But as @cliftonlabrum said, you can create your own controller with any of your custom views and logic, and present it.

Or you can also use the `AlertViewController` I provided as an extra, which is just a view controller like any other, but is already setup for having a Title Text, Body Text, and custom action's with 1 or 2 buttons. You can find out more about it in the readme.

Thanks for your patience, new version `2.0` is coming out really soon with a bunch of new features, refactors, improvements, and an updated easier to read documentation.

Thanks!
