### ISSUE TITLE
Swift 4.2 Support

### ISSUE THREAD

**Issue by sanju-naik** [IcaliaLabs/Presentr#157]
Looks like you guys are yet to release a version to support Swift 4.2? 

When I updated my project to Swift 4.2 with Presentr 1.3.2 Things are breaking, Any plans around releasing new version to support 4.2?

**Comment by mmcbrear** [comment]
bump

**Comment by danlozano** [comment]
done! let me know if there's any issue.

sorry for the wait, been really busy.
