### ISSUE TITLE
[Touch] unexpected nil

### ISSUE THREAD

**Issue by vkhadyka** [IcaliaLabs/Presentr#183]
I use your pod.
But sometime a got the next situation.
I show alert popup and can't dismiss it and console print log:
`[Touch] unexpected nil window in __sendSystemGestureLatentClientUpdate, _windowServerHitTestWindow: <UIWindow: 0x1063187b0; frame = (0 0; 375 812); autoresize = W+H; userInteractionEnabled = NO; gestureRecognizers = <NSArray: 0x281651dd0>; layer = <UIWindowLayer: 0x281ea7f80>>, touch:<UITouch: 0x10670fbf0> phase: Stationary tap count: 1 force: 1.133 window: (null) view: (null) location in window: {0, 0} previous location in window: {0, 0} location in view: {0, 0} previous location in view: {0, 0}`

And I have to relaunch my app. How can I fix it?

**Comment by patthehuman** [comment]
project is dead
