### ISSUE TITLE
Dismissing a custom view controller

### ISSUE THREAD

**Issue by TeplrGuy** [IcaliaLabs/Presentr#19]
Is it possible to dismiss a custom view controller from the left to right instead of from top to bottom? It seems like when i present it from right to left it still dismiss from top to bottom. What im trying to say is i want it to behave as if it was in a UINavigation controller. Thanks a bunch

**Comment by danlozano** [comment]
Hey!

Hmm, that is weird! What version are you using? That is definitely not the expected/correct behavior.

The default behavior for when you use a TransitionType is that the same transition that is used to present, is also used to dismiss, but reversed obviously.

So when you use the **.CoverHorizontalFromRight**, TransitionType it will present coming in from the right, and it will dismiss to the left. That is what should happen, and it is what happens in the Example project.

New in the latest version of Presentr is being able to set a dismissTransitionType, if you want a different transition for the dismissal.

**Comment by schmitzoide** [comment]
This is not working for me, although I have the animation defined for dismissing. Using Swift 3.0 and the latest release. Spent a couple of time here and I didn't manage to solve this.

**Comment by danlozano** [comment]
That's weird. You can download the repository and check out the example project. All of the samples have working presentation and dismissal transitions.

If you are using the latest release, the only other thing that occurs to me is if you're not holding a strong reference, as a property, to your Presentr object. Under the hood Presentr acts as a delegate for the presentation, if you have a local or weak Presentr object it will be deallocated and will not be around for the dismissal, hence the dismissal using the default system animation.

Could that be it in your case?
