### ISSUE TITLE
Carthage as an installation option? :)

### ISSUE THREAD

**Issue by selwin** [IcaliaLabs/Presentr#2]

**Comment by danlozano** [comment]
Good idea. I've never used carthage before but it would be nice to add it as an installation option as well. Let me look into it :)

**Comment by regynald** [comment]
This project already supports carthage. The only thing needed to add carthage support is making sure your Xcode schemes are shared, which they already are. 

I'll create a PR updating the readme.

**Comment by danlozano** [comment]
Awesome, thanks @regynald !
