### ISSUE TITLE
Can not use completion closure with this method customPresentViewController

### ISSUE THREAD

**Issue by tuyencoder** [IcaliaLabs/Presentr#22]
See this block, the completion param has been passing nil
```swift
private func presentViewController(presentingViewController presentingVC: UIViewController, presentedViewController presentedVC: UIViewController, animated: Bool, completion: (() -> Void)?){
        let transition = transitionType ?? presentationType.defaultTransitionType()
        if let systemTransition = transition.systemTransition(){
            presentedVC.modalTransitionStyle = systemTransition
        }
        presentedVC.transitioningDelegate = self
        presentedVC.modalPresentationStyle = .Custom
        presentingVC.presentViewController(presentedVC, animated: animated, completion: nil)
}
```

**Comment by tuyencoder** [comment]
Another finding is that 0.1.7 has not been in CocoaPods repo yet

**Comment by gabrielPeart** [comment]
@tuyencoder It has been fixed, will be merged soon

**Comment by danlozano** [comment]
@tuyencoder On your first point, @gabrielPeart has fixed it (thanks btw!) Will merge this in the next hour 👍 

On your second point, good catch! I had updated the podspec to 0.1.7 but I did not push it up to the Cocoapods master trunk. I just did it, so that should be fixed now.

**Comment by danlozano** [comment]
@gabrielPeart 's fix has been merged onto Develop.

Should be on Master/Release/Cocoapods soon 👍

**Comment by gabrielPeart** [comment]
@danlozano Cool! 👍

**Comment by danlozano** [comment]
Fixed!

https://github.com/IcaliaLabs/Presentr/releases/tag/0.1.8

**Comment by gabrielPeart** [comment]
👍
