### ISSUE TITLE
customPresentViewController completion is never called

### ISSUE THREAD

**Issue by fpg1503** [IcaliaLabs/Presentr#24]
The `completion` closure given to `customPresentViewController(_:viewController:animated:, completion:)` is never called.

**Comment by danlozano** [comment]
Hey!

Good catch. This has been fixed in #21 , amongst other things.

This has been merged into develop, will be merged onto master/release/cocoapods soon, possibly today.

👍

**Comment by danlozano** [comment]
Fixed!

https://github.com/IcaliaLabs/Presentr/releases/tag/0.1.8
