### ISSUE TITLE
How to put custom view inside

### ISSUE THREAD

**Issue by josejuanqm** [IcaliaLabs/Presentr#26]
like credit card screenshot on the readme?

**Comment by danlozano** [comment]
Hey @josejuanqm !

Good question.

I assume then, you are using the included AlertViewController, like shown in the readme.

But in reality, the intended or common use for Presentr is to be able to present your own View Controllers, which obviously have your own "custom" view inside of them.

You can create your View Controller in interface builder or in code, and then just use Presentr to present it, that't it!

```swift

class ViewController: UIViewController{

  let presenter: Presentr = {
      let presenter = Presentr(presentationType: .Alert)
      presenter.transitionType = .CoverHorizontalFromRight // Optional
      return presenter
  }()

  func showModal(){
    let controller = SomeCustomViewController()
    customPresentViewController(presenter, viewController: controller, animated: true, completion: nil)
  }

}

```

**Comment by danlozano** [comment]
Was that what you meant? @josejuanqm

**Comment by josejuanqm** [comment]
Great, Thanks!! thats exactly what i meant. @danlozano  👍

**Comment by levuhai** [comment]
How to add buttons in a custom pop up view? How to handle event by these buttons?

**Comment by gabrielPeart** [comment]
@levuhai 
If you check the PresentrExample you will be able to get familiar with the API.

You can present any UIViewController subclass (to have your custom pop up view). You handle events in the same way as you would handle in a normal UIViewController.
