### ISSUE TITLE
backgroundColor not showing, and transition type not as expected

### ISSUE THREAD

**Issue by niklassaers** [IcaliaLabs/Presentr#29]
Hey, thanks for making this wonderful Presentr. :-)

With 0.1.8 I want to modally display my view controller upon a view controller that is vended by an UINavigationController that is itself modally presented on top of another UINaviagationController backed stack. I present my view controller like this:

```
        let presenter: Presentr = {
            let width = ModalSize.Full
            let height = ModalSize.Custom(size: 393)
            let center = ModalCenterPosition.Center
            let customType = PresentationType.Custom(width: width, height: height, center: center)

            let customPresenter = Presentr(presentationType: customType)
            customPresenter.transitionType = .CoverHorizontalFromRight
            customPresenter.roundCorners = false
            customPresenter.backgroundColor = UIColor.redColor()
            customPresenter.backgroundOpacity = 0.7
            return customPresenter
        }()

        customPresentViewController(presenter, viewController: vc, animated: true, completion: nil)
```

and it appears fine, but the backgroundColor is black with alpha 0 according to the view debugger. When I was running 0.1.6, with the default background color there, I had the same issue.

From poking around a bit, it seems that ```private func presentationController(presented: UIViewController, presenting: UIViewController) -> PresentrController```is never called. ```private func presentViewController(presentingViewController presentingVC: UIViewController, presentedViewController presentedVC: UIViewController, animated: Bool, completion: (() -> Void)?)``` is called just fine, but none of the if clauses succeed, so I get neither ```systemPresentTransition``` nor ```systemDismissTransition```, which I expect is fine since I had it set to CoverHorizontalFromRight. Except that it does not cover from right either. When it comes up, it comes up from the bottom

Do you have any hints or pointers to what's going on and how I should use Presentr differently to get it presented with a background color and the expected animation?

Cheers

    Nik

**Comment by gabrielPeart** [comment]
I tried to add your configuration to our current PresentrExample project.
Where:

>      let presenter: Presentr = {
>         let width = ModalSize.Full
>         let height = ModalSize.Custom(size: 393)
>         let center = ModalCenterPosition.Center
>         let customType = PresentationType.Custom(width: width, height: height, center: center)
> 
>         let customPresenter = Presentr(presentationType: customType)
>         customPresenter.transitionType = .CoverHorizontalFromRight
>         customPresenter.roundCorners = false
>         customPresenter.backgroundColor = UIColor.redColor()
>         customPresenter.backgroundOpacity = 0.7
>         return customPresenter
>      }()
> 
>     // MARK: - IBAction's
> 
>     @IBAction func alertDefault(sender: UIButton) {
> 
>         //presenter.presentationType = .Alert
>         //presenter.transitionType = nil
>         //customPresentViewController(presenter, viewController: alertController, animated: true, completion: nil)
> 
>         customPresentViewController(presenter, viewController: alertController, animated: true, completion: nil)
>     }

And I got the attached result:

![simulator screen shot 11 aug 2016 16 54 27](https://cloud.githubusercontent.com/assets/194588/17592883/5b330a04-5fe4-11e6-93b9-730657d8430e.png)

As you can see, the background respects the defined color. Could you try to perform the same test using our current Master branch?

**Comment by niklassaers** [comment]
I have made a sample that recreates the problem from the master branch and will send it to you shortly

**Comment by niklassaers** [comment]
Have a look at https://www.dropbox.com/s/5peiklq9dhbsvqx/PresentrSample.zip?dl=0

See from Podfile that I use the latest commit on master
Open up PresentrSample.workspace, go to ViewController.swift and remove "/*" and "*/" that comment out the code around viewDidAppear. Launch the app in the simulator and see that a view controller with a yellow box with height 393 and red surroundings appears from right. Now go back to ViewController and comment it back in.

Relaunch the app, and hit the button "Tap me". See that the yellow view controller appears again, but is much more than 393 in height, appears from the bottom and has no red surroundings.

That last setting is what I see in my app too.

**Comment by gabrielPeart** [comment]
@niklassaers I noticed that if when you are performing the `customPresentViewController` in the `viewDidAppear` scope you trigger this issue. If you call if from a button action (just an example) it works perfectly.

I'll check it later, but seems to be connected to the fact that is not properly rendered in the moment when it is consumed. Could you give a try?

Thanks for reporting this use case.

**Comment by gabrielPeart** [comment]
@niklassaers could you try changing your TheModalViewController class to the following code:

```
import UIKit
import Presentr

class TheModalViewController: UIViewController {

    var vc: SomeViewController? = nil

    let presenter: Presentr = {
        let width = ModalSize.Full
        let height = ModalSize.Custom(size: 393)
        let center = ModalCenterPosition.Center
        let customType = PresentationType.Custom(width: width, height: height, center: center)

        let customPresenter = Presentr(presentationType: customType)
        customPresenter.transitionType = .CoverHorizontalFromRight
        customPresenter.roundCorners = false
        customPresenter.backgroundColor = UIColor.redColor()
        customPresenter.backgroundOpacity = 0.7
        return customPresenter
    }()

    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)

        if let vc = self.storyboard?.instantiateViewControllerWithIdentifier("SomeViewController") as? SomeViewController {
            self.vc = vc

            customPresentViewController(presenter, viewController: vc, animated: true, completion: nil)
        }
    }
}

```

In a nutshell I moved the Presentr outside the `viewDidAppear` scope to have time to be created in its plenitude.

**Comment by niklassaers** [comment]
Hi @gabrielPeart, thank for getting back to me so swiftly. :-) Your solution, as well as just delaying it with a dispatch_after in viewDidAppear both work great. :-) I must admit I do not understand why exactly, as at didAppear time I expect the view to be all right, but this solves the problem in my app and the example. :-) If you have the time to explain, I'd love to understand better why.

**Comment by gabrielPeart** [comment]
@niklassaers Glad to know that works. I believe that we could close this issue now :)
Of course, we can stay in touch and I can explain :)

**Comment by niklassaers** [comment]
Yupp, closed :-)

**Comment by danlozano** [comment]
Thanks for looking into this @gabrielPeart !

It's good that the work-around is working but I think I would like to look into why exactly it was happening and look into a fix por it. Maybe I should re-open and take a look.

:)
