### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by cosmo1234** [IcaliaLabs/Presentr#30]
How can i add image on the view

**Comment by danlozano** [comment]
Hi Cosmo,

Which view do you want to add an image to?

With Presentr you can present your own custom view controller with your own custom view created in code, or in interface builder.

If you are referring to the AlertViewController class included in the framework, that controller's view is currently not customizable, other than by settings the title, body and button texts.

**Comment by gabrielPeart** [comment]
@cosmo1234 You are able to present any UIViewController you want, which means that you can add an image, button, video, map, you name it as subview to it.
