### ISSUE TITLE
Full Swift3 Support

### ISSUE THREAD

**Issue by gabrielPeart** [IcaliaLabs/Presentr#32]

**Comment by b992** [comment]
+1

**Comment by kapellanos** [comment]
+1

**Comment by indiesk** [comment]
+1

**Comment by gabrielPeart** [comment]
Thanks for pointing it out! I'll be updating the swift3 branch very soon.

**Comment by u2194739** [comment]
+1

**Comment by ibeleliev** [comment]
+1

**Comment by ivanyorgov** [comment]
+1

**Comment by nfajardo** [comment]
+1

**Comment by eldelentes** [comment]
+1

**Comment by hunasdf** [comment]
+1

**Comment by danlozano** [comment]
Should have Swift 3.0 version live on master/cocoapods, and an alternative Swift 2.3 branch out between today and tomorrow!

Thanks for your patience!

**Comment by danlozano** [comment]
There are two new branches off of master right now.

**Swift3_gm** branch is working for now, if it's urgent you can point cocoapods to that branch. Still needs more testing before it's merged onto master and officially tagged for cocoapods (That should happen later on today).

There is also a working **Swift2.3** branch based on the 0.1.8 master branch release, if you need. That branch is probably not going to be maintained into the future, but if you need it for now there it is.

**Comment by gabrielPeart** [comment]
Hi guys, thanks for voting for it and supporting our library!
We are now officially releasing our new version with Swift 3 support :)
