### ISSUE TITLE
SWIFT 2.3 ios compatibility

### ISSUE THREAD

**Issue by sam961** [IcaliaLabs/Presentr#37]
Hi, 
why presenter 0.2.0 is not compatible with ios 8 ?

**Comment by writeincodes** [comment]
is there any branch supporting Swift2.3 ?

**Comment by sam961** [comment]
yes 0.2.0 but it supports > ios 9 ... I dont know why it dont support ios 8 too

**Comment by danlozano** [comment]
0.2.0 should support iOS 8 & Swift 2.3.

I'll fix the 0.2.0 podspec's as soon as possible.

**Comment by danlozano** [comment]
**Version 0.2.1** should be working with Coocapods. Disregard version 0.2.0.

It's the same code, just updated the Podspec to support iOS 8.0 and onward.

Let me know if you have any problems with it.

**Comment by kidsid-Ixigo** [comment]
Updating to 0.2.1 gives compiler errors on swift 2.3.
<img width="312" alt="screen shot 2016-10-04 at 3 14 38 pm" src="https://cloud.githubusercontent.com/assets/22613154/19069633/4f37edba-8a45-11e6-9be2-72a8f504abae.png">

**Comment by danlozano** [comment]
Are you sure you are in a Swift 2.3 project?

Because those errors are because in Swift 2.3 there are some small changes to the SDK. Some of them being that those delegate parameters are no longer optional.

Maybe 0.2.0/0.2.1 should be Swift 2.3 & iOS 9 onwards.

Let me look into it.

**Comment by kidsid-Ixigo** [comment]
Just cross checked and realised its swift v2.2. Sorry! By the way which version you will recommend then?

**Comment by danlozano** [comment]
Awesome! Was scared for a bit 😆 

Mmmm between 0.2.0 & 0.2.1 it's the same source code. The only difference is that 0.2.0 has a minimum target of iOS 9.0 on cocoapods and 0.2.1 has the minimum of iOS 8.0.

But what I really recommend is using Presentr v1.0.0, which is Swift 3.0 & iOS 9.0 onwards, as it's the only version that will be maintained onwards. But I realize that not everyone can make the switch to Swift 3.0 that quickly.

Thanks for using Presentr! Let me know if everything works out with version 0.2.1 and Swift 2.3, so I can close the issue for now.

**Comment by sam961** [comment]
Thank You, 0.2.1 is working with swift 2.3 on ios>=8
