### ISSUE TITLE
Initial loading lag

### ISSUE THREAD

**Issue by Joker666** [IcaliaLabs/Presentr#41]
Great library 👍 

I just tried to use the library, found out first time load has a some initial waiting lag, the later invocations are not hurt by this issue. I didn't get a chance to look into the code to see which function is taking time, but if this is a known issue, probably an updated readme would let everyone know about it :)

**Comment by danlozano** [comment]
Hey @Joker666 !

No, it's not really a known issue that I know of, but we should look into it to see what's happening.

Tell me a little bit more. Is the lag when you are presenting the provided AlertViewController class, or is it when you are presenting one of your own view controllers?

What presentation and animation type are you using?

Thanks 👍

**Comment by josejuanqm** [comment]
I also got this issue when working with big projects that had async tasks, maybe trying to dispatch to main?

**Comment by Joker666** [comment]
One of the provided AlertViewController class, I actually got the same problem in the example code, but I had to go to an old commit before 2.3 and 3.0 transition, since I am still using 2.2

**Comment by danlozano** [comment]
@Joker666 Ok, so the lag IS when you use the AlertViewController? Not when presenting your own view controllers?

I just want to investigate if the problem is with the AlertViewController itself, or with the Presentr presentation.

So just so I know, what Presentr version are you using? What iOS version, simulator, etc?

**Comment by Dwar3xwar** [comment]
I've also run into this problem while using the 3.0 update. This seems to be only an issue when running on a iPhone 5s device. Running it on the 6,6s,7,7s seems fine.

**Comment by sham3k** [comment]
Had the same problem.
It is not specific to this library. 
Use `DispatchQueue.main.async { self.customPresentViewController(...) }` for presenting View Controllers
