### ISSUE TITLE
example runned by show me error

### ISSUE THREAD

**Issue by bulolo** [IcaliaLabs/Presentr#43]
example runned by show me:

dyld: Library not loaded: @rpath/Presentr.framework/Presentr
  Referenced from: /var/containers/Bundle/Application/6D3D3E94-376B-4F63-B379-FC559F789D65/PresentrExample.app/PresentrExample
  Reason: image not found
(lldb)

**Comment by danlozano** [comment]
Hmmm...

So you're trying to run the example?

Try removing the framework (from the example project), and adding it back again. (You can build the framework, then reveal in finder, then drag to example project).

Let me know what happens!

**Comment by danlozano** [comment]
This will be fixed soon, importing framework into example project will be done via cocoapods.
