### ISSUE TITLE
Cannot run the Example

### ISSUE THREAD

**Issue by PhuocLinh** [IcaliaLabs/Presentr#47]
When I tried to build. It showed error: [https://www.dropbox.com/s/u3hg150x8u2y3xt/Screen%20Shot%202016-11-04%20at%203.17.32%20PM.png?dl=0](url)
by Xcode 8.1

**Comment by danlozano** [comment]
Hmmm

It say's that PresentrDelegate is an undeclared type. PresentrDelegate was a new type that came out on v1.0.1.

Can you do a pod update on the Example Project and see what happens?

Thanks!
