### ISSUE TITLE
empty tableview inside viewController with custom type

### ISSUE THREAD

**Issue by malkabani** [IcaliaLabs/Presentr#49]
hi
i have custom PresentationType with custom height and width
and inside it i have viewController that content tableview
this table view hasn't any data (some time have cells , and some times there are no cell to display)
if tableview hasn't any data then it should disable its scrole
but when user try to swipe tableview bug appear and the current view controller go to the top off screen
can help me please
thanks

**Comment by danlozano** [comment]
Hi @malkabani 

Are you using the latest version of Presentr ? 1.0.3 ? 

This could be an issue with the swipe to dismiss feature, that was disabled by default on the latest versions.

Could you update and see if it still happens?

Thanks!

**Comment by malkabani** [comment]
Hi @danlozano 
after make pod update this issue is fixed
thank you

**Comment by gabrielPeart** [comment]
@malkabani Nice, glad to know.
Thank you @danlozano
