### ISSUE TITLE
swift2.3crash

### ISSUE THREAD

**Issue by SeongBrave** [IcaliaLabs/Presentr#53]
Presentr Version	0.2.1 , ios 8.0  is crash when  dismissOnTap

```
  func chromeViewTapped(gesture: UIGestureRecognizer) {
        if gesture.state == .Ended && dismissOnTap {
            presentingViewController.dismissViewControllerAnimated(dismissAnimated, completion: nil)
        }
    }
```

**Comment by danlozano** [comment]
Hi @SeongBrave 

Thanks for the info!

Could you post the crash error message here to see what could be the problem?

**Comment by SeongBrave** [comment]
Hi @danlozano 
 there is not any error message, please you can get message for this picture
![image](https://cloud.githubusercontent.com/assets/10784393/21091327/73eaecea-c080-11e6-9a8e-a60d978bbfdd.png)

if you user Presentr version 0.2.1 on ios 8.0 device ,when you dismiss ,ti must be crash

**Comment by danlozano** [comment]
Interesting...

Let me look into it, thanks for the info!

**Comment by SeongBrave** [comment]
I am sorry, please
![20161213165129_1_20144325](https://cloud.githubusercontent.com/assets/10784393/21133602/8b47d9fa-c154-11e6-8bdb-71cd6326ec39.jpg)

**Comment by danlozano** [comment]
Still having this issue?

Swift 2.3 is no longer supported in Presentr but if it's a quick fix I'll can look into it.

But nothing comes to mind as what can be causing this.
