### ISSUE TITLE
how to make viewControllers contraint inside of overlay

### ISSUE THREAD

**Issue by pprevalon** [IcaliaLabs/Presentr#54]
how can i make viewController items constraint to the overlay top left right and bottom. Also when i present a view view controller over the overlay when that view controller dismiss i get the full view of the overlay and then it shrink. can this be fix.

**Comment by danlozano** [comment]
Hi!

When you create your own view controller in storyboard you can set up Auto-Layout on it's views the way you normally would.

Can you elaborate on the 2nd part. What is the "overlay" you are referring to? Do you have sample code or project I can use to check it out?

Thanks!
