### ISSUE TITLE
Question: More than two buttons

### ISSUE THREAD

**Issue by TheSDTM** [IcaliaLabs/Presentr#57]
Hello. Using origin Apple alert controller I can add more that 2 buttons and handle all of them. How can I do exactly the same using Presentr? As I can see, there is possible to use only 2 AlertActions. So, I think that it is possible to create new ViewControllers with buttons. But how should I handle them in my main ViewController? Thank you.

**Comment by danlozano** [comment]
Hey @TheSDTM !

Yeah, Apple's alert controller is **much** more full-featured unfortunately. Presentr's alert controller only has the option for one or two. Maybe in the future I will improve that, but there is no plan to do that at this moment.

You could just create your own view controller, use auto-layout on it to make sure it works well in any size, and then present it using Presentr.

To handle the buttons you could do two things.

- Create a "MyAlertControllerDelegate" protocol which transmits which button has been pressed.
```swift
protocol MyAlertControllerDelegate {
    func buttonPressed(sender: UIButton)
}
```
Then create a delegate property on your own view controller.
```swift
weak var delegate: MyAlertControllerDelegate?
```

- Your other option is using closures, which is what both Apple's and Presentr's alert controller uses.
```swift
class MyAlertController {
    var firstButtonPressed: ((sender: UIButton) -> Void)?
```
