### ISSUE TITLE
keyboardTranslationType and customPresentViewController is possible?

### ISSUE THREAD

**Issue by gabber3000** [IcaliaLabs/Presentr#64]
I can apply the `keyboardTranslationType = .moveUp inside` a `customPresentViewController(customPresenter, viewController: cambioPasswordcontroller, animated: true, completion: nil) ` unfortunately this does not seem to work. This is my code:
```
 let presenter: Presentr = {
        let presenter = Presentr(presentationType: .alert)
        presenter.transitionType = .coverHorizontalFromRight // Optional
        return presenter
        
      
    }()
    
    let customPresenter: Presentr = {
        let width = ModalSize.full
        //let height = ModalSize.custom(size: 150)
        let height = ModalSize.default
        let center = ModalCenterPosition.center
        let customType = PresentationType.custom(width: width, height: height, center: center)
        
        let customPresenter = Presentr(presentationType: customType)
        customPresenter.transitionType = .coverHorizontalFromRight
        customPresenter.dismissTransitionType = .coverHorizontalFromRight
        customPresenter.roundCorners = false
        customPresenter.keyboardTranslationType = .moveUp
    
       // customPresenter.backgroundColor = UIColor.green
       // customPresenter.backgroundOpacity = 0.5
        return customPresenter
    }()

 customPresentViewController(customPresenter, viewController: cambioPasswordcontroller, animated: true, completion: nil)
```
How can I solve this problem?
thank you

**Comment by danlozano** [comment]
Hi @gabber3000 

I think the issue is that the keyboardTranslation functionality has been activated and tested on only on the .popup type.

I'll look into making it work for other types, but I think custom presentation types are too vague (by design) so it would be complicated to design this functionality and have it work well on all cases.

But will definitely look into this and see what we can do. Thanks for bringing it into our attention.

**Comment by gabber3000** [comment]
Thank you for your help. Currently I have solved this problem by using this framework: [](https://github.com/hackiftekhar/IQKeyboardManager)
It seems to behave well.
Congratulations for the good work :)

**Comment by danlozano** [comment]
Interesting! I'm glad it worked out.

I'll check out the framework see what it's doing :) 

Thanks for using Presentr!

**Comment by v-ken** [comment]
@gabber3000 I have also tried to use IQKeyboardManager but when the keyboard dismisses, the Presentr view seems to be repositioned on the bottom left side of the screen. Was wondering if you had this issue as well and managed to solve it?

![simulator screen shot 21 apr 2017 1 00 41 pm](https://cloud.githubusercontent.com/assets/5682879/25260930/8b091578-2692-11e7-962c-ddd56a0e8d3e.png)

**Comment by v-ken** [comment]
Found the issue! `IQKeyboardManager` has the following code to save the current view controller's frame in `_topViewBeginRect`:

```swift
_topViewBeginRect = unwrappedRootController.view.frame

if shouldFixInteractivePopGestureRecognizer == true &&
    unwrappedRootController is UINavigationController &&
    unwrappedRootController.modalPresentationStyle != UIModalPresentationStyle.formSheet &&
    unwrappedRootController.modalPresentationStyle != UIModalPresentationStyle.pageSheet {

    if let window = keyWindow() {
        // Issue lies here - frame's origin is updated to a different value
        _topViewBeginRect.origin = CGPoint(x: 0,y: window.frame.size.height-unwrappedRootController.view.frame.size.height)
    } else {
        _topViewBeginRect.origin = CGPoint.zero
    }
}
```
Solution is to set `shouldFixInteractivePopGestureRecognizer` to false:

    IQKeyboardManager.sharedManager().shouldFixInteractivePopGestureRecognizer = false

**Comment by gabber3000** [comment]
thank you

**Comment by IanHoar** [comment]
I know this is a closed issue, but I'd like to add a request for supporting the `custom` type as well.  The way I see it is that it's an opt in API, and with proper documentation you could warn that it's not officially supported.  We're going to fork for now and remove the `type == .popup` check. I'll PR back anything that might make it in a reliable way for others.
