### ISSUE TITLE
Supporting iOS 8 with swift 3.0

### ISSUE THREAD

**Issue by arasu01** [IcaliaLabs/Presentr#65]
I have a project in swift 2.3 which used this library. It supports from iOS 8 and above.
Now I'm migrating the code to swift 3.0, but this library doesn't have swift 3.0 support for iOS 8.
How can use this library with swift3.0 support for iOS 8?

**Comment by danlozano** [comment]
Should be fixed in version 1.1.1 , just a quick fix in the Podspec.

Let me know if you have any problems.

Thanks! :)

**Comment by arasu01** [comment]
I was not able to install the latest version 1.1.1.

So I did pod search Presentr. I can't find the version 1.1.1 in that. Please find the attached image

**Comment by danlozano** [comment]
That's weird!

Maybe it took a while to get updated.

On the cocoapods website it lists it as 1.1.1

http://cocoapods.org/pods/Presentr

<img width="947" alt="screen shot 2017-02-06 at 8 05 31 pm" src="https://cloud.githubusercontent.com/assets/2406956/22674819/b79964b4-eca7-11e6-95f1-e889dd713998.png">

There it is! 👍
