### ISSUE TITLE
Custom background view

### ISSUE THREAD

**Issue by chlebta** [IcaliaLabs/Presentr#66]
is it possible to customise the background and use my own view instead of the black one ?

**Comment by danlozano** [comment]
Hey @chlebta 

You can change the background color and opacity with these two properties on your Presentr object.

```swift
presenter.backgroundColor = UIColor.red
presenter.backgroundOpacity = 1.0
```

Or you can choose to have a blurred out background with these other properties.

```swift
presenter.blurBackground = true
presenter.blurStyle = UIBlurEffectStyle.light
```
