### ISSUE TITLE
Swipe to dismiss not very responsive

### ISSUE THREAD

**Issue by otymartin** [IcaliaLabs/Presentr#67]
@danlozano 

I have my alert appearing from bottomhalf above my `ChatViewController` which uses a `UICollectionViewController`. i have `dissmissOnSwipe = true` but you really have to struggle or try multiple times before it can actually swipe/dismiss the presentr.

How come?

**Comment by danlozano** [comment]
Hey @otymartin 

Interesting. Let me look into it.

I'm planning to do a big refactor with some big new features in the coming weeks so I'll definitely have that in mind.

Can you share any more information about the issue. Does it always behave like that? or just in that case int that chat view controller? 

So I can try to reproduce.

Thanks for using Presentr! :)

**Comment by otymartin** [comment]
Hey its the same behaviour all around. For even in the examples I just added this to each alert and same behaviour. `presenter.dismissAnimated = true
 presenter.dismissOnSwipe = true`

Also topHalf alert requires swipe down to dismiss which should be swipeUp. 

The expected behaviour from my perspective is spoiled by apps like Snapchat. Where the swipe is pretty interactive and the whole alert view moves along with your finger on `downPress` until you completely swipe it off screen - check out Snapchat does it :)

If i was technically skilled I would do a PR but im not :(

**Comment by danlozano** [comment]
Hello!

Sorry for the late response, I've been really busy with work, but I'm taking this week off to work on my open source proyects.

- Just refactored the swipe to dismiss feature. I think the responsiveness is greatly improved. 👍 It should work kind of like Snapchat where it moves with your finger. If you move it enough, it dismisses, if not, it goes back to where it was.

- Also, all presentation types swipe DOWN but the topHalf swipes UP.

BUT,

- I don't think this feature will work well when you have a tableView, collectionView or a scrollView in your presented view controller as the swipe gesture will clash with the scroll view's. That is why the swipe to dismiss feature is turned off by default.

Thanks for your patience! The new release should be out sometime this week with this and many other improvements.

**Comment by otymartin** [comment]
@danlozano wow excellent I will try it out.
Thanks :) 👍
