### ISSUE TITLE
Popup moves after hiding keyboard

### ISSUE THREAD

**Issue by thierrybucco** [IcaliaLabs/Presentr#70]
Hi,

I am using Prensentr to display a TableView and a searchBar. It works well.
When I cancel search by touching Done in keyboard, popup moves on the left side.
See screenshot.

Do you have an idea ?

![1](https://cloud.githubusercontent.com/assets/12764744/23077875/443becd8-f514-11e6-94f2-cb3f1ab3d2c8.png)
![2](https://cloud.githubusercontent.com/assets/12764744/23077877/471ddf06-f514-11e6-8c2c-a90890779b86.png)

**Comment by thierrybucco** [comment]
Presentation type is:

`let presentationType: PresentationType = PresentationType.custom(width: ModalSize.sideMargin(value: 10), height: ModalSize.sideMargin(value: 30), center: .center)`

**Comment by danlozano** [comment]
Hi! Sorry for the late response, have been really busy with work, but I'm taking this whole week to look over all the issues and PR's. Thanks for your patience!

So basically it is working well, the presentation, dismissal, etc... 

The problem is that when you dismiss the keyboard, after searching, the popup moves to the left side?

If you have some sample code I can try out that would be of great help!

**Comment by mohammdsss1** [comment]
I am facing the same issue 

```
@discardableResult func presenter_show(controller: UIViewController, animated: Bool, size: CGSize? = nil, keyboard: KeyboardTranslationType = KeyboardTranslationType.none, backgroundOpacity: Float = 0.8) -> Presentr{
        let width = size == nil ? ModalSize.fluid(percentage: 0.8) : ModalSize.custom(size: Float(size!.width))
        let height = size == nil ? ModalSize.fluid(percentage: 0.9) : ModalSize.custom(size: Float(size!.height))
        let centerX = self.view.bounds.midX
        let centerY = self.view.bounds.midY
        let center = ModalCenterPosition.custom(centerPoint: CGPoint(x: centerX, y: centerY))
        let customType = PresentationType.custom(width: width, height: height, center: center)
        
        let presenter = Presentr(presentationType: customType)
        presenter.transitionType = nil
        presenter.dismissTransitionType = nil
        presenter.dismissAnimated = animated
        presenter.dismissOnTap = false
        presenter.roundCorners = false
        presenter.backgroundColor = backgroundOpacity == 0 ? .clear : UIColor.black.withAlphaComponent(CGFloat(backgroundOpacity))
        presenter.backgroundOpacity = backgroundOpacity
        presenter.keyboardTranslationType = keyboard
        
        customPresentViewController(presenter, viewController: controller, animated: animated, completion: nil)
        
        return presenter
    }
```

I tried all the enum values for the parameter `keyboard` and nothing changed!
