### ISSUE TITLE
Cannot set Shadow after Update

### ISSUE THREAD

**Issue by otymartin** [IcaliaLabs/Presentr#73]
@danlozano 
It seems I can no longer set a shadow.

In your new code, there is no initializers for the PresentrShadow struct.

**Comment by danlozano** [comment]
Good catch!

Will fix it right away. 👍 

I removed it because I thought, huh, this is not needed, struct's create an automatic memberwise initializer. BUUT aparently when you want that initializer to be public you have to do it yourself. Woops!

**Comment by danlozano** [comment]
Fixed in version 1.2.1

Thanks!
