### ISSUE TITLE
version 1.2.0 isn't on cocoapods

### ISSUE THREAD

**Issue by patthehuman** [IcaliaLabs/Presentr#77]
I just did a pod install and it pulled down v 1.0

Is it possible to use 1.2.0? I need the background view option

**Comment by danlozano** [comment]
hello!

hmmm I think that's how cocoapods works.

try using pod update Presentr

let me know fi that was it

**Comment by patthehuman** [comment]
Yeah I made a mistake and didnt update my pod repos :)
