### ISSUE TITLE
Background stays transparent if presentation is not animated

### ISSUE THREAD

**Issue by o15a3d4l11s2** [IcaliaLabs/Presentr#80]
If I call
`customPresentViewController(presenter, viewController: customViewController, animated: false, completion: nil)`
then I see no background at all.

If I just switch the `animated` to true, the alpha of the background becomes 1 and the background is visible.

The setup of the presenter is the following:
```
let presenter = Presentr(presentationType: .dynamic(center: .center))
presenter.backgroundColor = .yellow
presenter.backgroundOpacity = 0.5
```

**Comment by danlozano** [comment]
Hmm have not run into this. I'll see if I can replicate it.

I will look into this over the weekend.

**Comment by danlozano** [comment]
Hi!

I tried to recreate this with your exact code and it is working, the background is being set to yellow.

Can you provide a complete code sample / xcode project in which this is not working, to check it out further, and re-open the issue.

Thanks
