### ISSUE TITLE
PresentrShadow not initializing

### ISSUE THREAD

**Issue by deepakkghosh** [IcaliaLabs/Presentr#82]
The following code doesn't work:
`let shadow = PresentrShadow()
shadow.shadowColor = .black
shadow.shadowOpacity = 0.5
shadow.shadowOffset = CGSize(5,5)
shadow.shadowRadius = 4.0
presenter.dropShadow = shadow`
The error I get is: Cannot invoke initializer for type PresentrShadow with no arguments

Then I tried:
`let shadow = PresentrShadow(shadowColor: UIColor(CGColor: <>), shadowOpacity: <>, shadowOffset: <>, shadowRadius: <>)
        presenter.dropShadow = shadow`
The error I get is: Inaccessible due to internal protection level

I'm on 1.2.0. Help is much appreciated. Thanks!

**Comment by danlozano** [comment]
Hi!

This was fixed in version 1.2.1. Accidentally made the initializer private.
