### ISSUE TITLE
Delegate shouldPresentrDismiss called multiple times when swipeToDismiss is true.

### ISSUE THREAD

**Issue by kbjz** [IcaliaLabs/Presentr#85]
All in the title , when i swipe a view the delegate is called multiple times . I am working currently on flow Controller with Presentr so this crash all my navigation . Do i do something wrong ?
 
Thanks you for work btw .

Best

Kevin B.

**Comment by danlozano** [comment]
Hey Kevin,

Hmm that's weird.

So, with swipeToDismiss = true, while you are making the swipe gesture, the delegate gets called multiple times?

I'll look into this over the weekend.

**Comment by kbjz** [comment]
Ok thanks

**Comment by danlozano** [comment]
Fixed.

Should be out on next release.
