### ISSUE TITLE
Swift compiler error xCode 9.0 beta

### ISSUE THREAD

**Issue by ArturBaghdas** [IcaliaLabs/Presentr#86]
<img width="456" alt="screen shot 2017-06-06 at 2 32 33 pm" src="https://cloud.githubusercontent.com/assets/13787379/26825227/4135647c-4ac5-11e7-9292-5a3855d5a36a.png">

**Comment by danlozano** [comment]
This issue has been fixed on master branch in a backwards compatible way.

Will add to next cocoapod release over the weekend with this and other fixes.

:)

**Comment by ArturBaghdas** [comment]
Thanks
