### ISSUE TITLE
Can't use in objective-c

### ISSUE THREAD

**Issue by QB3L** [IcaliaLabs/Presentr#89]
I noticed PresentationType is not available in the objective-c header. The PresentationType enum is not marked @objc and additionally it contains functions inside so it makes sense for it not to make it into the header.

The final result is that the initWithPresentationType: is not there and I can't initialize a Presentr inside an objective-c class because of that.

Is this intended? If not I could try and work on a solution.

**Comment by danlozano** [comment]
Hello!

Hmmm yeah, never really thought of adding support for Objective-C for this project, don't really know where to start. Any help would be appreciated.
