### ISSUE TITLE
Pod install error [!] Unable to find a specification for `Presentr`

### ISSUE THREAD

**Issue by pratik6554** [IcaliaLabs/Presentr#9]
pod --version
1.0.0.beta.6

[!] Unable to find a specification for `Presentr`

**Comment by danlozano** [comment]
Hi!

That is strange. Are you on iOS 8.0 or above?

You get this error when trying to do a pod install?

**Comment by danlozano** [comment]
This issue could be related to a missing 
```ruby
use_frameworks!
```
in the Podfile? Since this is a Swift project.

**Comment by TGNA** [comment]
You can try this:
`pod 'Presentr',  :git => 'https://github.com/IcaliaLabs/Presentr.git'`
I worked for me.

**Comment by gabrielPeart** [comment]
Using:

`pod 'Presentr', '~> 0.1'`

Works just fine. Probably this issue should be closed.

**Comment by pratik6554** [comment]
@danlozano  Yes. I am using iOS 8 and above.
yes getting this error when i am trying to do a pod install
Sorry for late reply.

**Comment by gabrielPeart** [comment]
@pratik6554 Did you try using:

`pod 'Presentr', '~> 0.1'` ?

**Comment by pratik6554** [comment]
@gabrielPeart  No, same error.
pod 'Presentr', :git => 'https://github.com/IcaliaLabs/Presentr.git' worked.

**Comment by gabrielPeart** [comment]
@pratik6554 Could be something due to your pod version.
Glad to know that worked!

**Comment by pratik6554** [comment]
Thank you @gabrielPeart

**Comment by danlozano** [comment]
Hmm, this is strange. So the issue is fixed when you manually set the git address for the pod.

Anyone else have this issue?

**Comment by gabrielPeart** [comment]
Nope, haven't had any issue and I tested with different pod versions. Seems strange.
IMHO, should be closed and in case of similar issues we can re-evaluate

**Comment by danlozano** [comment]
@gabrielPeart Agreed!
