### ISSUE TITLE
Strange behavior for presenter

### ISSUE THREAD

**Issue by Mohammed-Eliass** [IcaliaLabs/Presentr#91]
I have added this code after installing pod `Presentr`
        
       let presenter = Presentr(presentationType: .popup)
        presenter.transitionType = .coverHorizontalFromRight
        presenter.dismissTransitionType = .coverVerticalFromTop
        presenter.dismissAnimated = true

        var popupViewController: PopupViewController = {
            let popupViewController = self.storyboard?.instantiateViewController(withIdentifier: "PopupViewController")
            return popupViewController as! PopupViewController
        }()

        customPresentViewController(presenter, viewController: popupViewController, animated: true, completion: nil)` 

but there's no popup, the view presented normally like iOS default present method with full screen width and height.

any ideas why this happened ??

**Comment by camanjj** [comment]
@Mohammed-Eliass make sure that you have a strong reference to the presenter, like keeping it as a property of the calling class. I ran into this same issue and that's how I resolved it

> It is important to hold on to the Presentr object as a property on the presenting/current View Controller since internally it will be used as a delegate for the custom presentation, so you must hold a strong reference to it.
