### ISSUE TITLE
change the size of the presented viewcontroller after a certain action

### ISSUE THREAD

**Issue by MaikoHermans** [IcaliaLabs/Presentr#97]
I currently have a popupview of which the view of the controller that is being presented should change after the user taps a certain button.

Let's say the presented view controller is 400 x 400 pixels and contains to buttons "yes" and "no". When the user presses "yes" the view controller will display some completely different content but it will also need to change to being 500 x 500 pixels.

Is it possible to achieve this?

**Comment by danlozano** [comment]
Hmm it should be possible just by modifying the presented view controller's frame.

If you run into any issues with this, or it does not work as expected please open a new issue and we'll look into it.

:)

**Comment by andreamazz** [comment]
Hi @danlozano 
I'm testing this out, and changing the frame doesn't seem to work. If I do it inside a UIView animation you can see that the frame changes but then the presenter enforces the starting size. Without animation there is no change at all. Any ideas?
